version: '4.37'

services:
  web:
    build: .  # dockerfile
    ports:
      - "8000:8000"
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code # todo el proyecto lo copia dentro de la carpeta code en el contenedor
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - webnet
  
  db:
    image: postgres:15
    volumes:
      - ../datosdjtnt:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=db_dj_tenant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456.*
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - webnet

networks:
  webnet: